PATH_DATASET = "/home/sergei/DataSet/"

'''
<CLASSIFIER>
'''
PATH_CLASSIFIER_NO_WELD = PATH_DATASET + "Set_no_weld/IMAGES/original/"

NP_SEED_CLASSIFIER = 1
SPLIT_SIZE_CLASSIFIER = 0.8
'''
</CLASSIFIER>
'''