PATH_DATASET = "/home/sergei/DataSet/"
'''
<CLASSIFIER>
'''
PATH_CLASSIFIER_NO_WELD = PATH_DATASET + "Set_no_weld/IMAGES/original/"

NP_SEED_CLASSIFIER = 1
SPLIT_SIZE_CLASSIFIER = 0.8
TRAIN_MODE_NPY_CLASSIFIER = True

IMG_SIZE_CLASSIFIER = [256, 306]  # origin shape=(2048, 2448, 3)
AUGMENTATION_FLIP_LEFT_RIGT = False
AUGMENTATION_FLIP_UP_DOWN = False
AUGMENTATION_NOISE = False
AUGMENTATION_NOISE_MEAN = 0
AUGMENTATION_NOISE_STDEV = 100




'''
</CLASSIFIER>
'''